max-players: 3
min-players: 2
countdown: 1
resources:
  brick:
    name: Кирпич
    timer: 1
    spawns:
      - "-15.5, 73, -1.5"
  iron:
    name: Железо
    timer: 5
    spawns:
      - "-15.5, 73, -3.5"
  gold:
    name: Золото
    timer: 10
    spawns:
      - "-15.5, 73, -5.5"
allowed-blocks:
  - GRASS_BLOCK
  - CUT_SANDSTONE
items:
  join-item:
    item-id: slime_ball
    name: "&a&lВойти в игру"
    lore:
      - "&7Нажмите ПКМ"
  select-team-item:
    item-id: magma_cream
    name: "&a&lВыбрать команду"
    lore:
      - "&7Нажмите ПКМ"
teams:
  red:
    name: Красные
    spawn: -223.5, 64, -86.5
    max-players: 1
  blue:
    name: Синие
    spawn: -226.5, 64, -89.5
    max-players: 1
arena:
  world: world
lobby:
  world: world
  spawn: -226.5, 64, -86.5