name: VnizCore
version: ${project.version}
main: my.nvinz.core.vnizcore.VnizCore
api-version: 1.13
authors: [nVinz]
description: Core Server Plugin
commands:
  none:
    description: leave team
  teams:
    description: show teams
  start:
    description: start game
  test:
    description: test command
  jointeam:
    description: choose team