name: VnizCore
version: ${project.version}
main: my.nvinz.core.vnizcore.VnizCore
api-version: 1.13
authors: [nVinz]
description: BedWars Minigame Plugin
commands:
  vniz:
    description: plugin command